# MySQL. Versions 5.1.10 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.7/en/old-client.html
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock

development:
  <<: *default
  database: tuto_app_development

test:
  <<: *default
  database: tuto_app_test

#
production:
  <<: *default
  database: tuto_app_production
  username: tuto_app
  password: <%= ENV['TUTO_APP_DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock
